In [2]:
%pip install catboost

Defaulting to user installation because normal site-packages is not writeable
Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from catboost) (2.3.5)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\programdata\anaconda3\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in c:\programdata\anaconda3\lib\site-packages (from catboost) (6.3.0)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\programdata\anaconda3\lib\site-packages (from plotly->catboost) (2.7.0)
Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 1.0/100.2 MB 6.8 MB/s eta 0:00:15
   - -------------------------------------- 2.6/100.2 MB 7.7 MB/s eta 0:00:13
   - -------------------------------------- 3.7/100.2 MB 6.8 MB/s eta 0:00:15
   - -------------------------------------- 5.0/100.2 MB 6.3 MB/s eta 0:00:16
   -- ------------------------------------- 6.0/100.2 MB 6.1 MB/s eta 0:00:16
   -- ------------------------------------- 7.1/100.2 MB 5.8 MB/s eta 0:00:17
   --- ------------------------------------ 7.9/100.2 MB 5.7 MB/s eta 0:00:17
   --- ------------------------------------ 8.7/100.2 MB 5.3 MB/s eta 0:00:18
   --- ------------------------------------ 9.7/100.2 MB 5.2 MB/s eta 0:00:18
   ---- ----------------------------------- 10.5/100.2 MB 5.0 MB/s eta 0:00:18
   ---- ----------------------------------- 11.3/100.2 MB 4.9 MB/s eta 0:00:19
   ---- ----------------------------------- 12.1/100.2 MB 4.9 MB/s eta 0:00:19
   ----- ---------------------------------- 12.6/100.2 MB 4.7 MB/s eta 0:00:19
   ----- ---------------------------------- 13.4/100.2 MB 4.7 MB/s eta 0:00:19
   ----- ---------------------------------- 14.4/100.2 MB 4.6 MB/s eta 0:00:19
   ------ --------------------------------- 15.2/100.2 MB 4.6 MB/s eta 0:00:19
   ------ --------------------------------- 16.3/100.2 MB 4.6 MB/s eta 0:00:19
   ------ --------------------------------- 16.8/100.2 MB 4.5 MB/s eta 0:00:19
   ------ --------------------------------- 17.3/100.2 MB 4.4 MB/s eta 0:00:19
   ------- -------------------------------- 18.4/100.2 MB 4.4 MB/s eta 0:00:19
   ------- -------------------------------- 19.1/100.2 MB 4.4 MB/s eta 0:00:19
   ------- -------------------------------- 19.9/100.2 MB 4.3 MB/s eta 0:00:19
   -------- ------------------------------- 20.7/100.2 MB 4.3 MB/s eta 0:00:19
   -------- ------------------------------- 21.8/100.2 MB 4.3 MB/s eta 0:00:19
   -------- ------------------------------- 22.5/100.2 MB 4.4 MB/s eta 0:00:18
   --------- ------------------------------ 23.6/100.2 MB 4.4 MB/s eta 0:00:18
   --------- ------------------------------ 24.4/100.2 MB 4.4 MB/s eta 0:00:18
   --------- ------------------------------ 24.9/100.2 MB 4.3 MB/s eta 0:00:18
   ---------- ----------------------------- 25.7/100.2 MB 4.2 MB/s eta 0:00:18
   ---------- ----------------------------- 26.7/100.2 MB 4.2 MB/s eta 0:00:18
   ---------- ----------------------------- 27.5/100.2 MB 4.2 MB/s eta 0:00:18
   ----------- ---------------------------- 28.0/100.2 MB 4.2 MB/s eta 0:00:18
   ----------- ---------------------------- 28.6/100.2 MB 4.1 MB/s eta 0:00:18
   ----------- ---------------------------- 29.1/100.2 MB 4.1 MB/s eta 0:00:18
   ----------- ---------------------------- 29.6/100.2 MB 4.1 MB/s eta 0:00:18
   ------------ --------------------------- 30.1/100.2 MB 4.0 MB/s eta 0:00:18
   ------------ --------------------------- 31.2/100.2 MB 4.0 MB/s eta 0:00:18
   ------------ --------------------------- 32.0/100.2 MB 4.0 MB/s eta 0:00:18
   ------------- -------------------------- 33.0/100.2 MB 4.0 MB/s eta 0:00:17
   ------------- -------------------------- 33.8/100.2 MB 4.0 MB/s eta 0:00:17
   ------------- -------------------------- 34.6/100.2 MB 4.0 MB/s eta 0:00:17
   -------------- ------------------------- 35.7/100.2 MB 4.0 MB/s eta 0:00:16
   -------------- ------------------------- 36.7/100.2 MB 4.1 MB/s eta 0:00:16
   -------------- ------------------------- 37.0/100.2 MB 4.0 MB/s eta 0:00:16
   --------------- ------------------------ 37.7/100.2 MB 4.0 MB/s eta 0:00:16
   --------------- ------------------------ 38.5/100.2 MB 4.0 MB/s eta 0:00:16
   --------------- ------------------------ 39.6/100.2 MB 4.0 MB/s eta 0:00:16
   ---------------- ----------------------- 40.4/100.2 MB 4.0 MB/s eta 0:00:15
   ---------------- ----------------------- 41.4/100.2 MB 4.0 MB/s eta 0:00:15
   ---------------- ----------------------- 42.2/100.2 MB 4.0 MB/s eta 0:00:15
   ----------------- ---------------------- 42.7/100.2 MB 4.0 MB/s eta 0:00:15
   ----------------- ---------------------- 43.8/100.2 MB 4.0 MB/s eta 0:00:15
   ----------------- ---------------------- 44.8/100.2 MB 4.0 MB/s eta 0:00:14
   ------------------ --------------------- 45.9/100.2 MB 4.0 MB/s eta 0:00:14
   ------------------ --------------------- 46.7/100.2 MB 4.1 MB/s eta 0:00:14
   ------------------- -------------------- 47.7/100.2 MB 4.1 MB/s eta 0:00:13
   ------------------- -------------------- 49.0/100.2 MB 4.1 MB/s eta 0:00:13
   ------------------- -------------------- 50.1/100.2 MB 4.1 MB/s eta 0:00:13
   -------------------- ------------------- 50.9/100.2 MB 4.1 MB/s eta 0:00:12
   -------------------- ------------------- 51.9/100.2 MB 4.1 MB/s eta 0:00:12
   --------------------- ------------------ 53.0/100.2 MB 4.1 MB/s eta 0:00:12
   --------------------- ------------------ 53.7/100.2 MB 4.1 MB/s eta 0:00:12
   --------------------- ------------------ 54.8/100.2 MB 4.2 MB/s eta 0:00:11
   ---------------------- ----------------- 55.8/100.2 MB 4.2 MB/s eta 0:00:11
   ---------------------- ----------------- 56.4/100.2 MB 4.2 MB/s eta 0:00:11
   ---------------------- ----------------- 57.1/100.2 MB 4.1 MB/s eta 0:00:11
   ----------------------- ---------------- 57.9/100.2 MB 4.1 MB/s eta 0:00:11
   ----------------------- ---------------- 59.0/100.2 MB 4.1 MB/s eta 0:00:10
   ----------------------- ---------------- 59.5/100.2 MB 4.1 MB/s eta 0:00:10
   ------------------------ --------------- 60.3/100.2 MB 4.1 MB/s eta 0:00:10
   ------------------------ --------------- 61.3/100.2 MB 4.1 MB/s eta 0:00:10
   ------------------------ --------------- 62.1/100.2 MB 4.1 MB/s eta 0:00:10
   ------------------------- -------------- 62.7/100.2 MB 4.1 MB/s eta 0:00:10
   ------------------------- -------------- 62.9/100.2 MB 4.1 MB/s eta 0:00:10
   ------------------------- -------------- 63.2/100.2 MB 4.1 MB/s eta 0:00:10
   ------------------------- -------------- 63.7/100.2 MB 4.0 MB/s eta 0:00:10
   ------------------------- -------------- 64.0/100.2 MB 4.0 MB/s eta 0:00:10
   ------------------------- -------------- 64.5/100.2 MB 3.9 MB/s eta 0:00:10
   ------------------------- -------------- 65.0/100.2 MB 3.9 MB/s eta 0:00:09
   -------------------------- ------------- 65.3/100.2 MB 3.9 MB/s eta 0:00:09
   -------------------------- ------------- 65.8/100.2 MB 3.9 MB/s eta 0:00:09
   -------------------------- ------------- 66.1/100.2 MB 3.8 MB/s eta 0:00:09
   -------------------------- ------------- 66.6/100.2 MB 3.8 MB/s eta 0:00:09
   -------------------------- ------------- 67.1/100.2 MB 3.8 MB/s eta 0:00:09
   -------------------------- ------------- 67.6/100.2 MB 3.8 MB/s eta 0:00:09
   --------------------------- ------------ 67.9/100.2 MB 3.8 MB/s eta 0:00:09
   --------------------------- ------------ 68.2/100.2 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 68.4/100.2 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 68.9/100.2 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 69.2/100.2 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 69.7/100.2 MB 3.6 MB/s eta 0:00:09
   ---------------------------- ----------- 70.3/100.2 MB 3.6 MB/s eta 0:00:09
   ---------------------------- ----------- 70.8/100.2 MB 3.6 MB/s eta 0:00:09
   ---------------------------- ----------- 71.0/100.2 MB 3.6 MB/s eta 0:00:09
   ---------------------------- ----------- 71.3/100.2 MB 3.6 MB/s eta 0:00:09
   ---------------------------- ----------- 71.8/100.2 MB 3.6 MB/s eta 0:00:08
   ---------------------------- ----------- 72.4/100.2 MB 3.5 MB/s eta 0:00:08
   ---------------------------- ----------- 72.6/100.2 MB 3.5 MB/s eta 0:00:08
   ----------------------------- ---------- 73.1/100.2 MB 3.5 MB/s eta 0:00:08
   ----------------------------- ---------- 73.7/100.2 MB 3.5 MB/s eta 0:00:08
   ----------------------------- ---------- 74.2/100.2 MB 3.5 MB/s eta 0:00:08
   ----------------------------- ---------- 74.4/100.2 MB 3.5 MB/s eta 0:00:08
   ----------------------------- ---------- 75.0/100.2 MB 3.5 MB/s eta 0:00:08
   ------------------------------ --------- 75.5/100.2 MB 3.4 MB/s eta 0:00:08
   ------------------------------ --------- 76.0/100.2 MB 3.4 MB/s eta 0:00:08
   ------------------------------ --------- 76.5/100.2 MB 3.4 MB/s eta 0:00:07
   ------------------------------ --------- 77.1/100.2 MB 3.4 MB/s eta 0:00:07
   ------------------------------ --------- 77.6/100.2 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 78.4/100.2 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 78.9/100.2 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 79.4/100.2 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 80.0/100.2 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 80.5/100.2 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 81.3/100.2 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 81.8/100.2 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 82.3/100.2 MB 3.4 MB/s eta 0:00:06
   --------------------------------- ------ 82.8/100.2 MB 3.4 MB/s eta 0:00:06
   --------------------------------- ------ 83.6/100.2 MB 3.4 MB/s eta 0:00:05
   --------------------------------- ------ 84.1/100.2 MB 3.4 MB/s eta 0:00:05
   --------------------------------- ------ 84.9/100.2 MB 3.3 MB/s eta 0:00:05
   ---------------------------------- ----- 85.7/100.2 MB 3.4 MB/s eta 0:00:05
   ---------------------------------- ----- 86.2/100.2 MB 3.3 MB/s eta 0:00:05
   ---------------------------------- ----- 86.8/100.2 MB 3.3 MB/s eta 0:00:05
   ---------------------------------- ----- 87.0/100.2 MB 3.3 MB/s eta 0:00:04
   ---------------------------------- ----- 87.6/100.2 MB 3.3 MB/s eta 0:00:04
   ----------------------------------- ---- 88.3/100.2 MB 3.3 MB/s eta 0:00:04
   ----------------------------------- ---- 89.4/100.2 MB 3.3 MB/s eta 0:00:04
   ------------------------------------ --- 90.4/100.2 MB 3.3 MB/s eta 0:00:03
   ------------------------------------ --- 91.5/100.2 MB 3.4 MB/s eta 0:00:03
   ------------------------------------ --- 92.5/100.2 MB 3.4 MB/s eta 0:00:03
   ------------------------------------- -- 93.6/100.2 MB 3.4 MB/s eta 0:00:02
   ------------------------------------- -- 94.6/100.2 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 95.7/100.2 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 96.5/100.2 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 97.0/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  98.0/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  99.4/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 100.2/100.2 MB 3.4 MB/s  0:00:29
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   ---------------------------------------- 2/2 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21
Note: you may need to restart the kernel to use updated packages.

In [4]:
from catboost import CatBoostRegressor

In [6]:
%pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
    --------------------------------------- 0.8/48.9 MB 2.7 MB/s eta 0:00:18
   - -------------------------------------- 1.6/48.9 MB 2.8 MB/s eta 0:00:17
   - -------------------------------------- 2.1/48.9 MB 2.9 MB/s eta 0:00:17
   -- ------------------------------------- 3.1/48.9 MB 3.2 MB/s eta 0:00:15
   --- ------------------------------------ 3.9/48.9 MB 3.3 MB/s eta 0:00:14
   ---- ----------------------------------- 5.0/48.9 MB 3.5 MB/s eta 0:00:13
   ---- ----------------------------------- 6.0/48.9 MB 3.8 MB/s eta 0:00:12
   ----- ---------------------------------- 7.1/48.9 MB 3.9 MB/s eta 0:00:11
   ------ --------------------------------- 8.4/48.9 MB 4.2 MB/s eta 0:00:10
   ------- -------------------------------- 9.4/48.9 MB 4.4 MB/s eta 0:00:10
   -------- ------------------------------- 11.0/48.9 MB 4.4 MB/s eta 0:00:09
   --------- ------------------------------ 11.5/48.9 MB 4.5 MB/s eta 0:00:09
   ---------- ----------------------------- 12.3/48.9 MB 4.3 MB/s eta 0:00:09
   ---------- ----------------------------- 12.8/48.9 MB 4.2 MB/s eta 0:00:09
   ----------- ---------------------------- 13.6/48.9 MB 4.1 MB/s eta 0:00:09
   ----------- ---------------------------- 14.2/48.9 MB 4.0 MB/s eta 0:00:09
   ----------- ---------------------------- 14.7/48.9 MB 3.9 MB/s eta 0:00:09
   ------------ --------------------------- 14.9/48.9 MB 3.8 MB/s eta 0:00:09
   ------------ --------------------------- 15.5/48.9 MB 3.7 MB/s eta 0:00:10
   ------------- -------------------------- 16.3/48.9 MB 3.6 MB/s eta 0:00:09
   ------------- -------------------------- 16.8/48.9 MB 3.6 MB/s eta 0:00:09
   -------------- ------------------------- 17.3/48.9 MB 3.6 MB/s eta 0:00:09
   -------------- ------------------------- 18.1/48.9 MB 3.5 MB/s eta 0:00:09
   --------------- ------------------------ 18.6/48.9 MB 3.5 MB/s eta 0:00:09
   --------------- ------------------------ 19.4/48.9 MB 3.5 MB/s eta 0:00:09
   ---------------- ----------------------- 19.9/48.9 MB 3.5 MB/s eta 0:00:09
   ---------------- ----------------------- 20.7/48.9 MB 3.5 MB/s eta 0:00:09
   ----------------- ---------------------- 21.2/48.9 MB 3.5 MB/s eta 0:00:08
   ----------------- ---------------------- 22.0/48.9 MB 3.5 MB/s eta 0:00:08
   ------------------ --------------------- 22.8/48.9 MB 3.5 MB/s eta 0:00:08
   ------------------- -------------------- 23.3/48.9 MB 3.5 MB/s eta 0:00:08
   ------------------- -------------------- 24.1/48.9 MB 3.5 MB/s eta 0:00:08
   -------------------- ------------------- 24.9/48.9 MB 3.5 MB/s eta 0:00:07
   -------------------- ------------------- 25.7/48.9 MB 3.5 MB/s eta 0:00:07
   --------------------- ------------------ 26.2/48.9 MB 3.4 MB/s eta 0:00:07
   ---------------------- ----------------- 27.0/48.9 MB 3.5 MB/s eta 0:00:07
   ---------------------- ----------------- 27.5/48.9 MB 3.4 MB/s eta 0:00:07
   ----------------------- ---------------- 28.3/48.9 MB 3.4 MB/s eta 0:00:07
   ----------------------- ---------------- 28.8/48.9 MB 3.4 MB/s eta 0:00:06
   ------------------------ --------------- 29.6/48.9 MB 3.4 MB/s eta 0:00:06
   ------------------------ --------------- 30.4/48.9 MB 3.4 MB/s eta 0:00:06
   ------------------------- -------------- 30.9/48.9 MB 3.4 MB/s eta 0:00:06
   ------------------------- -------------- 31.7/48.9 MB 3.4 MB/s eta 0:00:06
   -------------------------- ------------- 32.5/48.9 MB 3.4 MB/s eta 0:00:05
   --------------------------- ------------ 33.3/48.9 MB 3.4 MB/s eta 0:00:05
   --------------------------- ------------ 33.8/48.9 MB 3.4 MB/s eta 0:00:05
   ---------------------------- ----------- 34.6/48.9 MB 3.4 MB/s eta 0:00:05
   ---------------------------- ----------- 35.1/48.9 MB 3.4 MB/s eta 0:00:05
   ----------------------------- ---------- 35.9/48.9 MB 3.4 MB/s eta 0:00:04
   ----------------------------- ---------- 36.7/48.9 MB 3.4 MB/s eta 0:00:04
   ------------------------------ --------- 37.2/48.9 MB 3.4 MB/s eta 0:00:04
   ------------------------------ --------- 37.7/48.9 MB 3.4 MB/s eta 0:00:04
   ------------------------------- -------- 38.3/48.9 MB 3.4 MB/s eta 0:00:04
   ------------------------------- -------- 38.8/48.9 MB 3.3 MB/s eta 0:00:04
   -------------------------------- ------- 39.3/48.9 MB 3.3 MB/s eta 0:00:03
   -------------------------------- ------- 39.6/48.9 MB 3.3 MB/s eta 0:00:03
   -------------------------------- ------- 39.8/48.9 MB 3.3 MB/s eta 0:00:03
   -------------------------------- ------- 40.1/48.9 MB 3.2 MB/s eta 0:00:03
   -------------------------------- ------- 40.4/48.9 MB 3.2 MB/s eta 0:00:03
   --------------------------------- ------ 40.6/48.9 MB 3.2 MB/s eta 0:00:03
   --------------------------------- ------ 40.6/48.9 MB 3.2 MB/s eta 0:00:03
   --------------------------------- ------ 40.9/48.9 MB 3.1 MB/s eta 0:00:03
   --------------------------------- ------ 41.4/48.9 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 41.7/48.9 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 42.2/48.9 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 42.5/48.9 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 42.7/48.9 MB 3.0 MB/s eta 0:00:03
   ----------------------------------- ---- 43.0/48.9 MB 2.9 MB/s eta 0:00:03
   ----------------------------------- ---- 43.3/48.9 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 43.5/48.9 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 44.0/48.9 MB 2.9 MB/s eta 0:00:02
   ------------------------------------ --- 44.3/48.9 MB 2.9 MB/s eta 0:00:02
   ------------------------------------ --- 44.8/48.9 MB 2.8 MB/s eta 0:00:02
   ------------------------------------ --- 45.1/48.9 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 45.4/48.9 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 45.6/48.9 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 46.1/48.9 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 46.4/48.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 46.9/48.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 47.2/48.9 MB 2.7 MB/s eta 0:00:01
   -------------------------------------- - 47.7/48.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  48.0/48.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  48.2/48.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 48.9/48.9 MB 2.6 MB/s  0:00:18
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1
Note: you may need to restart the kernel to use updated packages.

In [7]:
from xgboost import XGBRegressor

In [8]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [9]:
df = pd.read_csv('data/stud.csv')

In [10]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [11]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [12]:
X = df.drop(['math_score'] , axis = 1)

In [13]:
X

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,99,95
996,male,group C,high school,free/reduced,none,55,55
997,female,group C,high school,free/reduced,completed,71,65
998,female,group D,some college,standard,completed,78,77
999,female,group D,some college,free/reduced,none,86,86

In [14]:
y = df['math_score']
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [15]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
         ("StandardScaler", numeric_transformer, num_features),        
    ]
)

In [16]:
X = preprocessor.fit_transform(X)

In [17]:
X.shape

(1000, 19)

In [18]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((800, 19), (200, 19))